config/routes.rb
Isg2::Application.routes.draw do
  root to: "node#index"

  get "node" => "node#index"
  match "node/create" => "node#create", via: [:get, :post]
  match "node/edit" => "node#edit", via: [:get, :post]
  match "node/graphview" => "node#graphview", via: [:get]
  match "node/getData" => "node#getData", via: [:get]
  match "node/import" => "node#import", via: [:get, :post]
  post "/node/paste"
  delete "node/removeAll"
  delete "node/destroy"

  match "resource/create" => "resource#create", via: [:get, :post]
  match "resource/edit" => "resource#edit", via: [:get, :post]
  delete "resource/destroy"
  get "resource/:id/open" => "resource#open", as: :resource_open
  get "resource/getBreadcrumbs"

  get "complaint" => "complaint#index"
  match "complaint/create" => "complaint#create", via: [:get, :post]
  delete "complaint/destroy"
  match "complaint/ticket" => "complaint#ticket", via: [:get, :post]
  get "complaint/chart"
  get "complaint/getComplaintData"
  post "complaint/:id/update_status" => "complaint#update_status", as: :complaint_update_status
  post "complaint/:id/assign_admin" => "complaint#assign_admin", as: :complaint_assign_admin

  get "logout" => "application#logout"

  get "admin" => "admin#index"
  match "admin/create" => "admin#create", via: [:get, :post]
  match "admin/search" => "admin#search", via: [:get, :post]
  match "admin/destroy" => "admin#destroy", via: [:get, :post]
  
  match "message" => "message#index", via: [:get, :post]
  match "message/create" => "message#create", via: [:get, :post]
  match "message/:id/reply" => "message#reply", as: :message_reply, via: [:get, :post]
  match "message/destroy" => "message#destroy", via: [:get, :post]

  get "announcement" => "announcement#index"
  get "announcement/:id/notice" => "announcement#notice"
  match "announcement/create" => "announcement#create", via: [:get, :post]
  match "announcement/:id/edit" => "announcement#edit", via: [:get, :post], as: :announcement_edit
  delete "announcement/:id/destroy" => "announcement#destroy", as: :announcement_destroy
  match "announcement/notice" => "announcement#notice", via: [:get, :post]
  post "announcement/:id/toggle_show" => "announcement#toggle_show", as: :announcement_toggle_show

  get "query" => "query#index"
  match "query/create" => "query#create", via: [:get, :post]
  delete "query/:id/destroy" => "query#destroy", as: :query_destroy
  match "query/:id/edit" => "query#edit", as: :query_edit, via: [:get, :post]
  match "query/run" => "query#run", as: :query_run, via: [:get, :post]
end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
  belongs_to :admin

  attr_accessible :admin, :title, :description, :shown_on_homepage
  validates :admin, :title, :description, :presence => true
  validates_inclusion_of :shown_on_homepage, in: [true, false]

  before_save :default_values
  before_create :default_values
  before_validation :default_values
  def default_values
    self.shown_on_homepage = true if self.shown_on_homepage.nil?
    return
  end
end

app/controllers/announcement_controller.rb
class AnnouncementController < ApplicationController
  before_filter CASClient::Frameworks::Rails::Filter, except: [:index, :notice]

  before_filter :check_admin_privilege, except: [:index, :notice]

  def index
    @notices = Announcement.all
  end

  def notice
    begin
      @notice = Announcement.find(params[:id])
    rescue
      flash[:errors] << "Could not find announcement with id '#{params[:id]}'"
      redirect_to announcement_path
    end
  end

  def create
    if request.method == "POST"
      new_announcement = @admin.announcements.new(
        :title => params[:title],
        :description => params[:description]
      )

      if new_announcement.save
        flash[:notice] = "Successfully submitted announcement '#{new_announcement.title}'."
        redirect_to announcement_path
      else
        new_announcement.errors.map do |k, v|
          flash[:errors] << "#{k} error: #{v}."
        end
      end
    end
  end

  def edit
    begin
      @announcement = Announcement.find(params[:id])
    rescue
      flash[:errors] << "Could not find announcement with id '#{params[:id]}'"
      redirect_to announcement_path and return
    end

    if request.method == "POST"
      @announcement.title = params[:title]
      @announcement.description = params[:description]
      if @announcement.save
        flash[:notice] = "Successfully updated announcement '#{@announcement.title}'."
        redirect_to announcement_path
      else
        @announcement.errors.map do |k, v|
          flash[:errors] << "#{k} error: #{v}."
        end
      end
    end
  end

  def destroy
    begin
      announcement = Announcement.find(params[:id])
      if announcement.destroy
        flash[:notice] = "Successfully removed announcement '#{announcement.title}'"
      else
        flash[:errors] << "Can't remove announcement '#{announcement.title}'"
      end
    rescue
      flash[:errors] << "Could not find announcement with id '#{params[:id]}'"
    end
    redirect_to announcement_path
  end

  def toggle_show
    begin
      announcement = Announcement.find(params[:id])
      announcement.toggle!(:shown_on_homepage)
      if announcement.shown_on_homepage
        flash[:notice] = "Announcement '#{announcement.title}' will be shown on homepage"
      else
        flash[:notice] = "Announcement '#{announcement.title}' won't be shown on homepage"
      end
    rescue
      flash[:errors] << "Could not find announcement with id '#{params[:id]}'"
    end
    redirect_to announcement_path
  end
end

app/views/announcement/create.html.erb
<% provide(:title, 'Create announcement') %>

<h2>Create new announcement</h2>
<% if flash[:notice] %>
  <div id='notice' class='alert alert-success'><%= flash[:notice] %></div>
<% end %>
<% if flash[:error] or !flash[:errors].blank? %>
  <div id='error' class='alert alert-error'>
    <ul>
      <% if flash[:error] %>
        <li><%= flash[:error] %></li>
      <% end %>
      <% if flash[:errors] %>
        <% flash[:errors].each do |error| %>
          <li><%= error %></li>
        <% end %>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_tag announcement_create_path do %>
  <%= label_tag :title, 'Title: ' %>
  <%= text_field_tag :title %><br />
  <%= label_tag :description, 'Description: ' %>
  <%= text_area_tag :description, nil, rows: "10", cols: "25"%><br />
  <%= submit_tag 'Submit', class: "btn btn-primary" %>
  &nbsp; &nbsp;
  <%= link_to "Back", announcement_path, method: :get, class: "btn btn-primary" %>
<% end %>

app/views/announcement/edit.html.erb
<% provide(:title, 'Edit announcement') %>

<h2>Edit Announcement</h2>
<% if flash[:notice] %>
  <div id='notice' class='alert alert-success'><%= flash[:notice] %></div>
<% end %>
<% if flash[:error] or !flash[:errors].blank? %>
  <div id='error' class='alert alert-error'>
    <ul>
      <% if flash[:error] %>
        <li><%= flash[:error] %></li>
      <% end %>
      <% if flash[:errors] %>
        <% flash[:errors].each do |error| %>
          <li><%= error %></li>
        <% end %>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_tag announcement_edit_path(@announcement.id) do %>
  <%= label_tag :title, 'Title: ' %>
  <%= text_field_tag :title, @announcement.title %><br />
  <%= label_tag :description, 'Description: ' %>
  <%= text_area_tag :description, @announcement.description, rows: "10", cols: "25"%><br />
  <%= submit_tag 'Save announcement', class: "btn btn-primary" %>
  &nbsp; &nbsp;
  <%= link_to "Back", announcement_path, method: :get, class: "btn btn-primary" %>
<% end %>

app/views/announcement/index.html.erb
<% provide(:title, 'Announcements') %>

<% if flash[:notice] %>
  <div id='notice' class='alert alert-success'><%= flash[:notice] %></div>
<% end %>
<% if flash[:error] or !flash[:errors].blank? %>
  <div id='error' class='alert alert-error'>
    <ul>
      <% if flash[:error] %>
        <li><%= flash[:error] %></li>
      <% end %>
      <% if flash[:errors] %>
        <% flash[:errors].each do |error| %>
          <li><%= error %></li>
        <% end %>
      <% end %>
    </ul>
  </div>
<% end %>

<% if @admin %>
	<table>
		<tr>
			<th>
				<%= link_to "Add Announcement", announcement_create_path, class: "btn btn-primary" %>
			</th>
		</tr>
	</table>
	<br>
<% end %>

<% unless @notices.blank? %>
	<table class="table table-stripped table-hover table-condensed">
		<thead>
			<tr>
				<th>Submitted Date</th>
				<th>Title</th>
				<th>Shown on homepage?</th>
			</tr>
		</thead>
		<tbody>
				<% @notices.each do |notice| %> 
					<tr>
						<td><%= notice.created_at %></td>
						<td><%= notice.title %></td>
						<td>
							<a href=<%=announcement_toggle_show_path(notice.id)%> data-method="post">
								<%= check_box_tag "", "", notice.shown_on_homepage %>
							</a>
						</td>

						<td>
							<button class="btn btn-small btn-info" onclick="displayEditAnnouncement(<%= notice.id %>, '<%= j notice.title %>' , '<%= j notice.description %>' )" type="button">
							Edit Notice
						</button>
						</td>
						<td>
							<button class="btn btn-small btn-danger" onclick="displayRemoveAnnouncement(<%= notice.id %>, '<%= j notice.title %>' )" type="button">
							Remove
						</button>
						</td>
					</tr>
				<% end %>
		</tbody>
	</table>
<% else %>
	There are no announcements!
<% end %>

<!-- Remove Announement -->
  <div id="removeAnnouncement" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="removeAnnouncement" aria-hidden="true">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      <h3>Remove Announcement</h3>
    </div>
    <div class="modal-body">
      <%= form_tag "/", :method => :delete, id: "destroy_form" do %>
        <p>Do you want to remove the announcement '<span class="announcement_name"></span>'?</p>
      </div>
      <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
        <%= submit_tag 'Delete', :class => "btn btn-danger btn-primary" %>
      </div>
      <% end %>   
  </div>

<!-- Edit Announement -->
  <div id="editAnnouncement" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="editAnnouncement" aria-hidden="true">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      <h3>Edit Announcement</h3>
    </div>
    <div class="modal-body">
      <%= form_tag "/", id: "edit_form" do %>
      <%= label_tag 'Title: ' %>
  		<%= text_field_tag :title %><br />
  		<%= label_tag 'Description: ' %>
  		<%= text_area_tag :description, rows: "10", cols: "25"%><br />
      </div>
      <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
        <%= submit_tag 'Save', :class => "btn btn-primary" %>
      </div>
      <% end %>   
  </div>

<script type="text/javascript">
  	//Show the the comfirm for remove
	function displayRemoveAnnouncement(id, title) {
		$('#removeAnnouncement').modal();
		$('#destroy_form').attr("action", '/announcement/'+id+'/destroy')
		$('#removeAnnouncement .modal-body .announcement_name').text(title);	
	}

	//Show the edit form
	function displayEditAnnouncement(id, title, description) {
		$('#editAnnouncement').modal();
		$('#edit_form').attr("action", '/announcement/'+id+'/edit')
		$('#editAnnouncement .modal-body #title').val(title);
		$('#editAnnouncement .modal-body #description').val(description);	
	}
</script>

app/views/announcement/notice.html.erb
<% provide(:title, 'Announcement details') %>

<div>
  <h2><%= @notice.title %></h2>
  <h5>Description:</h5>
  <%= @notice.description %>
	<br/><br/>

	<%= link_to "Back", root_path, method: :get, class: "btn btn-small btn-primary" %>
</div>