config/routes.rb
Isg2::Application.routes.draw do
  root to: "node#index"

  get "node" => "node#index"
  match "node/create" => "node#create", via: [:get, :post]
  match "node/edit" => "node#edit", via: [:get, :post]
  match "node/graphview" => "node#graphview", via: [:get]
  match "node/getData" => "node#getData", via: [:get]
  match "node/import" => "node#import", via: [:get, :post]
  post "/node/paste"
  delete "node/removeAll"
  delete "node/destroy"

  match "resource/create" => "resource#create", via: [:get, :post]
  match "resource/edit" => "resource#edit", via: [:get, :post]
  delete "resource/destroy"
  get "resource/:id/open" => "resource#open", as: :resource_open
  get "resource/getBreadcrumbs"

  get "complaint" => "complaint#index"
  match "complaint/create" => "complaint#create", via: [:get, :post]
  delete "complaint/destroy"
  match "complaint/ticket" => "complaint#ticket", via: [:get, :post]
  get "complaint/chart"
  get "complaint/getComplaintData"
  post "complaint/:id/update_status" => "complaint#update_status", as: :complaint_update_status
  post "complaint/:id/assign_admin" => "complaint#assign_admin", as: :complaint_assign_admin

  get "logout" => "application#logout"

  get "admin" => "admin#index"
  match "admin/create" => "admin#create", via: [:get, :post]
  match "admin/search" => "admin#search", via: [:get, :post]
  match "admin/destroy" => "admin#destroy", via: [:get, :post]
  
  match "message" => "message#index", via: [:get, :post]
  match "message/create" => "message#create", via: [:get, :post]
  match "message/:id/reply" => "message#reply", as: :message_reply, via: [:get, :post]
  match "message/destroy" => "message#destroy", via: [:get, :post]

  get "announcement" => "announcement#index"
  get "announcement/:id/notice" => "announcement#notice"
  match "announcement/create" => "announcement#create", via: [:get, :post]
  match "announcement/:id/edit" => "announcement#edit", via: [:get, :post], as: :announcement_edit
  delete "announcement/:id/destroy" => "announcement#destroy", as: :announcement_destroy
  match "announcement/notice" => "announcement#notice", via: [:get, :post]
  post "announcement/:id/toggle_show" => "announcement#toggle_show", as: :announcement_toggle_show

  get "query" => "query#index"
  match "query/create" => "query#create", via: [:get, :post]
  delete "query/:id/destroy" => "query#destroy", as: :query_destroy
  match "query/:id/edit" => "query#edit", as: :query_edit, via: [:get, :post]
  match "query/run" => "query#run", as: :query_run, via: [:get, :post]
end

app/views/admin/index.html.erb
<% provide(:title, 'Users List') %>

<% if flash[:notice] %>
  <div id='notice' class='alert alert-success'><%= flash[:notice] %></div>
<% end %>
<% if flash[:error] or !flash[:errors].blank? %>
  <div id='error' class='alert alert-error'>
    <ul>
      <% if flash[:error] %>
        <li><%= flash[:error] %></li>
      <% end %>
      <% if flash[:errors] %>
        <% flash[:errors].each do |error| %>
          <li><%= error %></li>
        <% end %>
      <% end %>
    </ul>
  </div>
<% end %>

<%= link_to "Add admin by looking up name", admin_search_path, class: "btn btn-primary" %>
<h2>Users</h2>
<br>
<table class="table table-stripped table-hover table-condensed">
  <thead>
    <tr>
      <th>Full Name</th>
      <th>Calnet ID</th>
      <th>Email</th>
    </tr>
  </thead>
  <tbody>
    <% unless @users.blank? %>
      <% @users.each do |user| %> 
        <tr class="warning" >
          <td><%= user.fullname %></td>
          <td><%= user.calnetID %></td>

          <% if user.email %>
            <td>
              <%= user.email %>
            </td>
            <td>
              <%= link_to("Add Admin", admin_create_path(fullname: user.fullname, email: user.email, calnetID: user.calnetID), :method => :post, :title => "Make this user becomes an admin") %>
            </td>
          <% else %>
            <%= form_tag admin_create_path, method: :get, class: "form-inline" do %>
              <%= hidden_field_tag :fullname, user.fullname %>
              <%= hidden_field_tag :calnetID, user.calnetID %>
              <td>
                <%= email_field_tag :email, nil, placeholder: "Email required!" %>
              </td>
              <td>
                <%= submit_tag "Save email & add as Admin", class: "btn btn-small btn-info btn-primary" %>
              </td>
            <% end %>
          <% end %>
          
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>
<br>
<br>

<h2>Admins</h2>
<br>
<table class="table table-stripped table-hover table-condensed">
  <thead>
    <tr>
      <th>Full Name</th>
      <th>Calnet ID</th>
      <th>Email</th>
    </tr>
  </thead>
  <tbody>
    <% unless @admins.blank? %>
      <% @admins.each do |admin| %> 
        <tr class="success" >
          <td><%= admin.fullname %></td>
          <td><%= admin.calnetID %></td>
          <td><%= admin.email %></td>
          <th>
            <%= link_to("Remove Admin", admin_destroy_path(id: admin), :method => :post, :title => "This removes the admin") %> 
          </th>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/admin/search.html.erb
<% provide(:title, 'Search names to add to admin list') %>

<h2>Add admin by name</h2>
<br />

<% if flash[:notice] %>
  <div id='notice' class='alert alert-success'><%= flash[:notice] %></div>
<% end %>
<% if flash[:error] or !flash[:errors].blank? %>
  <div id='error' class='alert alert-error'>
    <ul>
      <% if flash[:error] %>
        <li><%= flash[:error] %></li>
      <% end %>
      <% if flash[:errors] %>
        <% flash[:errors].each do |error| %>
          <li><%= error %></li>
        <% end %>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_tag admin_search_path do %>
  <%= label_tag :first_name, 'First name: ' %>
  <%= text_field_tag :first_name, params[:first_name] %>
  <%= label_tag :last_name, 'Last name: ' %>
  <%= text_field_tag :last_name, params[:last_name] %><br />
  <%= submit_tag 'Search', class: "btn btn-primary" %>
  &nbsp; &nbsp;
  <%= link_to "Back", admin_path, method: :get, class: "btn btn-primary" %>
<% end %>

<% if @ldap_entries %>
  <table class="table table-stripped table-hover table-condensed">
    <thead>
      <tr>
        <th>Full Name</th>
        <th>Calnet ID</th>
        <th>Email</th>
      </tr>
    </thead>
    <tbody>
      <% @ldap_entries.each do |ldap_entry| %> 
        <tr class=<%= Admin.find_by_calnetID(ldap_entry.uid.first).nil? ? "warning" : "success"%> >
          <td><%= ldap_entry.displayName.first %></td>
          <td><%= ldap_entry.uid.first %></td>
          <td><%= ldap_entry.mail.first if ldap_entry.attribute_names.include?(:mail) %></td>
          <td class="span2"></td>
          <td><%= displayAddAdminLinkFromLDAP(ldap_entry) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>