config/routes.rb
Isg2::Application.routes.draw do
  root to: "node#index"

  get "node" => "node#index"
  match "node/create" => "node#create", via: [:get, :post]
  match "node/edit" => "node#edit", via: [:get, :post]
  match "node/graphview" => "node#graphview", via: [:get]
  match "node/getData" => "node#getData", via: [:get]
  match "node/import" => "node#import", via: [:get, :post]
  post "/node/paste"
  delete "node/removeAll"
  delete "node/destroy"

  match "resource/create" => "resource#create", via: [:get, :post]
  match "resource/edit" => "resource#edit", via: [:get, :post]
  delete "resource/destroy"
  get "resource/:id/open" => "resource#open", as: :resource_open
  get "resource/getBreadcrumbs"

  get "complaint" => "complaint#index"
  match "complaint/create" => "complaint#create", via: [:get, :post]
  delete "complaint/destroy"
  match "complaint/ticket" => "complaint#ticket", via: [:get, :post]
  get "complaint/chart"
  get "complaint/getComplaintData"
  post "complaint/:id/update_status" => "complaint#update_status", as: :complaint_update_status
  post "complaint/:id/assign_admin" => "complaint#assign_admin", as: :complaint_assign_admin

  get "logout" => "application#logout"

  get "admin" => "admin#index"
  match "admin/create" => "admin#create", via: [:get, :post]
  match "admin/search" => "admin#search", via: [:get, :post]
  match "admin/destroy" => "admin#destroy", via: [:get, :post]
  
  match "message" => "message#index", via: [:get, :post]
  match "message/create" => "message#create", via: [:get, :post]
  match "message/:id/reply" => "message#reply", as: :message_reply, via: [:get, :post]
  match "message/destroy" => "message#destroy", via: [:get, :post]

  get "announcement" => "announcement#index"
  get "announcement/:id/notice" => "announcement#notice"
  match "announcement/create" => "announcement#create", via: [:get, :post]
  match "announcement/:id/edit" => "announcement#edit", via: [:get, :post], as: :announcement_edit
  delete "announcement/:id/destroy" => "announcement#destroy", as: :announcement_destroy
  match "announcement/notice" => "announcement#notice", via: [:get, :post]
  post "announcement/:id/toggle_show" => "announcement#toggle_show", as: :announcement_toggle_show

  get "query" => "query#index"
  match "query/create" => "query#create", via: [:get, :post]
  delete "query/:id/destroy" => "query#destroy", as: :query_destroy
  match "query/:id/edit" => "query#edit", as: :query_edit, via: [:get, :post]
  match "query/run" => "query#run", as: :query_run, via: [:get, :post]
end

app/models/complaint.rb
class Complaint < ActiveRecord::Base
  belongs_to :user
  belongs_to :admin
  has_many :messages

  attr_accessible :ip_address, :status, :title, :user, :admin, :user_email, :admin_id

  validates :ip_address, :status, :title, :user, :presence => true
  validates :status, :inclusion => { :in => ["new", "read", "assigned", "in progress", "completed"] }

  before_save :default_values
  before_create :default_values
  before_validation :default_values
  def default_values
    self.status = "new" if self.status.nil?
    return
  end
end

app/controllers/complaint_controller.rb
class ComplaintController < ApplicationController
	# This requires the user to be authenticated for viewing all pages.
  before_filter CASClient::Frameworks::Rails::Filter

  before_filter :check_admin_privilege, only: [:chart, :getComplaintData]
  before_filter :setup_session_info # Somehow before_filter in application_controller doesn't work

  def update_status
    begin
      @complaint = Complaint.find(params[:id])
    rescue
      flash[:error] = "Could not find complaint with id '#{params[:id]}'"
      redirect_to complaint_path and return
    end
    if params[:status]
      unless @complaint.update_attributes(status: params[:status])
        flash[:error] = "Couldn't update status of complaint #{@complaint.id} to '#{params[:status]}'"
      else
        flash[:notice] = "Status of Complaint '#{@complaint.title}' updated."
      end
    else
      flash[:error] = "Parameter status missing"
    end
    redirect_to complaint_path
  end

  def assign_admin
    begin
      @complaint = Complaint.find(params[:id])
    rescue
      flash[:error] = "Could not find complaint with id '#{params[:id]}'"
      redirect_to complaint_path and return
    end
    if params[:status]
      unless @complaint.update_attributes(status: params[:status])
        flash[:error] = "Couldn't update status of complaint #{@complaint.id} to '#{params[:status]}'"
      else
        flash[:notice] = "Status of Complaint '#{@complaint.title}' updated."
      end
    else
      flash[:error] = "Parameter status missing"
    end
    if params[:owner]
      unless @complaint.update_attributes(admin_id: params[:owner])
        flash[:error] = "Couldn't assign complaint #{@complaint.id} to admin #{params[:owner]}"
      else
        flash[:notice] = "Assigned Complaint '#{@complaint.title}' to Admin #{params[:owner]}."
      end
    else
      flash[:error] = "Parameter owner missing"
    end
    redirect_to complaint_path
  end

	def index
    if @admin
      if params[:id]
        @complaints = Complaint.find_all_by_admin_id(params[:id])
      else
        @complaints = Complaint.all()
      end
      @list_admins= Admin.all()
    elsif @user
      @complaints = Complaint.find_all_by_user_id(@user)
    else
      flash[:error] = "Must login to view your list of complaints"
    end
  end

	def create
    if @admin
      flash[:error] = "Only normal user can create complaint"
    elsif @user
      if params[:title] and params[:description]
    		new_complaint = @user.complaints.new(
    			:title => params[:title],
          :user_email => params[:user_email],
    			:ip_address => @remote_ip,
    			:status => "new"	
    	  )
        unless new_complaint.save
          flash[:error] = new_complaint.errors.map {|k,v| "#{k.to_s} error: #{v}"}.join(". ")
          return
        end

        first_message = new_complaint.messages.new(
          :user => @user,
          :content => params[:description],
        )
        if first_message.save
          flash[:notice] = "Successfully submitted complaint '#{new_complaint.title}'."
        else
          flash[:error] = first_message.errors.map {|k,v| "#{k.to_s} error: #{v}"}.join(". ")
          new_complaint.destroy
          return
      	end
      else
        # Go to the form for creating complaints
        return
      end
    else
      flash[:error] = "Have to logged in as a normal user to submit ticket"
    end
    redirect_to complaint_path
	end

	def destroy
    begin
		  @complaint = Complaint.find(params[:id])
    rescue
      flash[:error] = "Could not find complaint with id '#{params[:id]}'"
      redirect_to complaint_path and return
    end

		complaint_title = @complaint.title
		@complaint.destroy

    flash[:notice] = "Successfully removed complaint '#{complaint_title}'."
    redirect_to complaint_path
	end

	def getComplaintData
		data = {}
		totalComplaints = {}
		totalResolved = {}
		totalUnresolved = {}
		Complaint.all().each do |complaint| 
			date = complaint.created_at.to_date.to_s.gsub('-', '/')
			if totalComplaints[date]
				totalComplaints[date] += 1
				if totalResolved[date] and complaint.status == "completed"
					totalResolved[date] += 1
				elsif totalUnresolved[date] and complaint.status == "new"
					totalUnresolved[date] += 1
				end
			else
				totalComplaints[date] = 1
				if complaint.status == "completed"
					totalResolved[date] = 1
					totalUnresolved[date] = 0
				elsif complaint.status == "new"
					totalUnresolved[date] = 1
					totalResolved[date] = 0
				end
			end
		end
		data[:totalComplaints] = totalComplaints
		data[:totalResolved] = totalResolved
		data[:totalUnresolved] = totalUnresolved
		respond_to do |format|
			format.json {render :json => data}
		end
	end
end

app/helpers/complaint_helper.rb
module ComplaintHelper
	def getComplaintRowColor(state)
		color = state == "completed" ? "success" : "warning"
		return color.html_safe
	end

	def displayContent(complaint_id)
		current_complaint = Complaint.find_by_id(complaint_id)
		messages = Message.ordered_by_complaint(complaint_id)
		content = "<table><tr><td><h2>#{h(current_complaint.title)}</h2></td><td><div class=\"span7\"></div></td>"
		content << "<td><button class=\"btn btn-primary\" onclick=\"displayMessagesForm(#{h(messages[-1].id)})\">Reply</button></td></table>"
		content << "<h5>Description:</h5>"
		content << "<div class=complaint>#{h(messages[0].content)}</div>"
		content.html_safe
	end

	def displayMessages(complaint_id)
		messages = Message.ordered_by_complaint(complaint_id)
		messages.shift
		html_code = "<table class=\"table table-stripped table-hover table-condensed\">"
		html_code << "<tr>"
		html_code << "<th class='span2'>Message no.</th>"
		html_code << "<th class='span3'>Author</th>"
		html_code << "<th class='span7'>Content</th>"
		html_code << "</tr>"
		messages.each do |message|
			html_code << "<tr>"
			author = message.admin || message.user
			html_code << "<td class='span2'>#{message.depth}</td>"
			html_code << "<td class='span3'>#{author.fullname}</td>"
			html_code << "<td class='span7'>#{message.content}</td>"
			html_code << "</tr>"
		end
		html_code << "</table>"
		html_code.html_safe
	end

	def backbutton()
		back = "<a class=\"btn btn-small btn-primary\" href=\"#{h(complaint_path)}\" data-method=\"get\">Back</a>"
		back.html_safe
	end

	def displayAdmin(admin_id)
		admin = Admin.find_by_id(admin_id)
		if not admin.nil?
			html_code = "#{admin.fullname}"
			html_code.html_safe
		end
	end
end

app/views/complaint/chart.html.erb
<% provide(:title, 'Complaint Chart') %>
<head>
  <%= javascript_include_tag 'https://www.google.com/jsapi', 'custom.complaintChart' %>
</head>
<center>
  <h3>Complaints Chart</h3>
</center>
<div id="chartRangeFilter_dashboard_div" style="border: 1px solid #ccc">
  <table class="columns">
    <tr>
      <td>
        <div id="chartRangeFilter_chart_div" style="width: 1116px; height: 300px;"></div>
      </td>
    </tr>
    <tr>
      <td>
        <div id="chartRangeFilter_control_div" style="width: 1116px; height: 50px;"></div>
      </td>
    </tr>
  </table>
</div>
<br/>
<%= backbutton() %>

<script type="text/javascript">
  drawChart();
</script>

app/views/complaint/create.html.erb
<h2>Complaint Form</h2>
<% if flash[:notice] %>
  <div id='notice' class='alert alert-success'><%= flash[:notice] %></div>
<% end %>
<% if flash[:error] %>
  <div id='error' class='alert alert-error'><%= flash[:error] %></div>
<% end %>
<%= form_tag "/complaint/create" do %>
  <%= label_tag :title, 'Title: ' %>
  <%= text_field_tag :title %><br />
  <%= label_tag :user_email, 'Your email: ' %>
  <%= email_field_tag :user_email, @user.email %><br />
  <%= label_tag :description, 'Description: ' %>
  <%= text_area_tag :description, nil, :rows => "10", :cols => "25"%><br />
  <%= submit_tag 'Submit' ,:class => "btn btn-large btn-primary" %>
<% end %>

app/views/complaint/index.html.erb
<% provide(:title, 'Complaints Management') %>
<% if flash[:notice] %>
      <div id='notice' class='alert alert-success'><%= flash[:notice] %></div>
<% end %>
<% if flash[:error] %>
      <div id='error' class='alert alert-error'><%= flash[:error] %></div>
<% end %>
<table>
	<tr>
		<% unless @user_admin %>
			<th><button class="btn btn-primary" onclick="displayTicketForm()" type="button">Submit Ticket</button></th>
		<% end %>
		<% if @user_admin %>
			<th><button class="btn btn-primary" onclick="displayChart()" type="button">Display Chart</button></th>
			<th>&nbsp;&nbsp;</th>
			<th>
			<div class="btn-group">
				<a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
					View
					<span class="caret"></span>
				</a>
				<ul class="dropdown-menu">
					<%= link_to "All", complaint_path %>
					<% @list_admins.each do |admin| %>
						<%= link_to admin.fullname, complaint_path(id: admin) %>
					<% end %>
				</ul>
			</div>
			</th>
	<% end %>
	</tr>
</table>
<br>
<table class="table table-stripped table-hover table-condensed">
	<thead>
		<tr>
			<th>Submitted Date</th>
			<th>IP_Address</th>
			<th>Title</th>
			<th>Status</th>
			<% if @user_admin %>
				<th>Owner</th>
			<% end %>
		</tr>
	</thead>
	<tbody>
		<% unless @complaints.blank? %>
			<% @complaints.each do |complaint| %> 
				<tr class=<%=getComplaintRowColor(complaint.status)%> >
					<td><%= complaint.created_at %></td>
					<td><%= complaint.ip_address %></td>
					<td><%= complaint.title %></td>
					<td><%= complaint.status %></td>
					<td>
						<% if @user_admin %>
							<% if complaint.status == "new" %>
								<div class="btn-group">
									<a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
										Assign
										<span class="caret"></span>
									</a>
									<ul class="dropdown-menu">
										<% @list_admins.each do |admin| %>
											<%= link_to admin.fullname, complaint_assign_admin_path(complaint, status: "assigned", owner: admin), method: :post %>
										<% end %>
									</ul>
								</div>
							<% else %>
								<%= displayAdmin(complaint.admin_id) %>
							<% end %>
						<% end %>
					</td>
					<td>
						<% if @user_admin and not complaint.admin_id.nil? %>
							<div class="btn-group">
								<a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
									Update
									<span class="caret"></span>
								</a>
								<ul class="dropdown-menu">
									<% ["read", "in progress", "completed"].each do |status| %>
										<%= link_to status, complaint_update_status_path(complaint, status: status), method: :post %>
									<% end %>
								</ul>
							</div>
						<% end %>
					</td>
					<td>
						<button class="btn btn-small btn-info" onclick="displayTicket(<%= complaint.id %>)" type="button">
							Content
						</button>
					</td>
					<td>
						<button class="btn btn-small btn-danger" onclick="displayRemoveComplaint(<%= complaint.id %>, '<%= j complaint.title %>')" type="button">
							Remove
						</button>
					</td>
				</tr>
			<% end %>
		<% end %>
	</tbody>
</table>

<!-- Remove Complaint -->
  <div id="removeComplaint" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="removeComplaint" aria-hidden="true">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      <h3>Remove Complaint</h3>
    </div>
    <div class="modal-body">
      <%= form_tag '/complaint/destroy', :method => :delete do %>
        <%= hidden_field_tag :id %>
        <p>Do you want to remove the complaint '<span class="complaint_name"></span>'?</p>
      </div>
      <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
        <%= submit_tag 'Delete', :class => "btn btn-danger btn-primary" %>
      </div>
      <% end %>   
  </div>

<script type="text/javascript">

	//Show the ticket form
	function displayTicketForm() {
	  var url = "/complaint/create";
	  $(location).attr('href', url);
	}

	//Show the ticket content
	function displayTicket(id) {
	  var url = "/complaint/ticket?cid=" + id;
	  $(location).attr('href', url);
	}

	//Show a complaint chart
	function displayChart() {
	  var url = "/complaint/chart";
	  $(location).attr('href', url);
	}

	//Show the the comfirm for remove
	function displayRemoveComplaint(id, name) {
		$('#removeComplaint').modal();
		$('#removeComplaint .modal-body #id').val(id);
		$('#removeComplaint .modal-body .complaint_name').text(name);	
	}

</script>

app/views/complaint/list_all.html.erb
<% provide(:title, 'Complaints Management') %>
<%= button_to "Submit a Ticket", complaint_create_path, :method => "get", :class => "btn btn-large btn-primary" %>
<table class="table table-stripped table-hover table-condensed">
	<thead>
		<tr>
			<th>Submited Date</th>
			<th>IP_Address</th>
			<th>Title</th>
			<th>Resolved</th>
		</tr>
	</thead>
	<tbody>
		<% unless @complaints.blank? %>
			<% @complaints.each do |complaint| %> 
				<tr class=<%=getRowColor(complaint.isResolved)%> >
					<td><%= complaint.created_at %></td>
					<td><%= complaint.ip_address %></td>
					<td><%= complaint.title %></td>
					<td><%= isResolved(complaint.isResolved) %></td>
				</tr>
			<% end %>
		<% end %>
	</tbody>
</table>

app/views/complaint/ticket.html.erb
<% provide(:title, 'User Complaint Ticket') %>
<div>
	<%= displayContent(params[:cid]) %>
  	<%= displayMessages(params[:cid]) %>
  	</br></br></br>
	<%= backbutton() %>
</div>

<!-- Reply Form -->
  <div id="replyForm" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="replyForm" aria-hidden="true">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      <h3>Reply</h3>
    </div>
    <div class="modal-body">
      <%= form_tag "/", id: "reply_form" do %>
  		<%= label_tag 'Reply: ' %>
  		<%= text_area_tag :content, nil, rows: "10", cols: "25"%><br />
      </div>
      <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
        <%= submit_tag 'Submit', :class => "btn btn-primary" %>
      </div>
      <% end %>   
  </div>

<script type="text/javascript">
	//Show the reply form
	function displayMessagesForm(id) {
		$('#replyForm').modal();
		$('#reply_form').attr("action", '/message/'+id+'/reply')
	}
</script>