config/routes.rb
Isg2::Application.routes.draw do
  root to: "node#index"

  get "node" => "node#index"
  match "node/create" => "node#create", via: [:get, :post]
  match "node/edit" => "node#edit", via: [:get, :post]
  match "node/graphview" => "node#graphview", via: [:get]
  match "node/getData" => "node#getData", via: [:get]
  match "node/import" => "node#import", via: [:get, :post]
  post "/node/paste"
  delete "node/removeAll"
  delete "node/destroy"

  match "resource/create" => "resource#create", via: [:get, :post]
  match "resource/edit" => "resource#edit", via: [:get, :post]
  delete "resource/destroy"
  get "resource/:id/open" => "resource#open", as: :resource_open
  get "resource/getBreadcrumbs"

  get "complaint" => "complaint#index"
  match "complaint/create" => "complaint#create", via: [:get, :post]
  delete "complaint/destroy"
  match "complaint/ticket" => "complaint#ticket", via: [:get, :post]
  get "complaint/chart"
  get "complaint/getComplaintData"
  post "complaint/:id/update_status" => "complaint#update_status", as: :complaint_update_status
  post "complaint/:id/assign_admin" => "complaint#assign_admin", as: :complaint_assign_admin

  get "logout" => "application#logout"

  get "admin" => "admin#index"
  match "admin/create" => "admin#create", via: [:get, :post]
  match "admin/search" => "admin#search", via: [:get, :post]
  match "admin/destroy" => "admin#destroy", via: [:get, :post]
  
  match "message" => "message#index", via: [:get, :post]
  match "message/create" => "message#create", via: [:get, :post]
  match "message/:id/reply" => "message#reply", as: :message_reply, via: [:get, :post]
  match "message/destroy" => "message#destroy", via: [:get, :post]

  get "announcement" => "announcement#index"
  get "announcement/:id/notice" => "announcement#notice"
  match "announcement/create" => "announcement#create", via: [:get, :post]
  match "announcement/:id/edit" => "announcement#edit", via: [:get, :post], as: :announcement_edit
  delete "announcement/:id/destroy" => "announcement#destroy", as: :announcement_destroy
  match "announcement/notice" => "announcement#notice", via: [:get, :post]
  post "announcement/:id/toggle_show" => "announcement#toggle_show", as: :announcement_toggle_show

  get "query" => "query#index"
  match "query/create" => "query#create", via: [:get, :post]
  delete "query/:id/destroy" => "query#destroy", as: :query_destroy
  match "query/:id/edit" => "query#edit", as: :query_edit, via: [:get, :post]
  match "query/run" => "query#run", as: :query_run, via: [:get, :post]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <div id="online_counter">
      <%= pluralize(@online_people, 'person') %> online, <%= pluralize(@online_registered, 'user') %> registered
    </div>
    <h5>Copyright 2013 </h5>
    <p>Phuc-Hai Lu Huynh, Minh Luong, Jacky Ng, Jimmy Wu</p>
  </small>
</footer>

app/views/layouts/_header.html.erb
<header>
<div class="navbar navbar-inverse navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
		  <a class="brand" href="/">ISG 2.0</a>
		  <ul class="nav">
		    <li class="active"><a href="/">Home</a></li>
		    <li><a href="http://inst.eecs.berkeley.edu/~inst/" class="iframe">About Us</a></li>
		    <li><a href="http://inst.eecs.berkeley.edu/faq.html" class="iframe">FAQ</a></li>
		  </ul>
			<form class="navbar-form pull-right" method="post" action=<%=@login_url%>>
		  	<% if @user %>
			  	Welcome, <%= @user.fullname %>!
	  			(<a href=<%=logout_path%>>Sign out</a>)
	  			<br>
	  			<a href=<%=complaint_path%>>Manage Complaints</a>
	  		<% elsif @admin %>
	  			Welcome, Admin <%= @admin.fullname %>!
	  			(<a href=<%=logout_path%>>Sign out</a>)
	  			<br>
	  			<a href=<%=complaint_path%>>Manage Complaints</a> |
	  			<a href=<%=announcement_path%>>Announcements</a> |
	  			<a href=<%=admin_path%>>Admins</a> |
	  			<a href=<%=query_path%>>Queries</a>
	  		<% else %>
	  			<button type="submit" id="CALNET" class="btn">CalNet</button>
	  		<% end %>
		  </form>
		</div>
	</div>
</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= stylesheet_link_tag 'custom', 'http://fonts.googleapis.com/css?family=Raleway:400,500,600,300' %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
  <% if Rails.env.development? %>
    <!-- <%= debug(params) %>
    <pre>
      <%= @list_admins.inspect %>
      <%= @json_content.inspect %>
    </pre> -->
  <% end %>
</body>
</html>